// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplicationAchats.Models;

#nullable disable

namespace WebApplicationAchats.Migrations
{
    [DbContext(typeof(VenteContext))]
    [Migration("20251217105921_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplicationAchats.Models.Categorie", b =>
                {
                    b.Property<int>("CategorieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategorieId"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategorieId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("WebApplicationAchats.Models.Client", b =>
                {
                    b.Property<int>("Numcli")
                        .HasColumnType("int")
                        .HasColumnName("NUMCLI");

                    b.Property<string>("Categorie")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CATEGORIE");

                    b.Property<string>("Compte")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("COMPTE");

                    b.Property<string>("Nomcli")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NOMCLI");

                    b.Property<string>("Ville")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("VILLE");

                    b.HasKey("Numcli")
                        .HasName("PK__CLIENT__64C8A28346C65F99");

                    b.ToTable("CLIENT", (string)null);
                });

            modelBuilder.Entity("WebApplicationAchats.Models.Clientadress", b =>
                {
                    b.Property<int>("Numcli")
                        .HasColumnType("int")
                        .HasColumnName("NUMCLI");

                    b.Property<string>("Address1")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ADDRESS1");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("STATE");

                    b.HasKey("Numcli")
                        .HasName("pk_ClientAddr");

                    b.ToTable("CLIENTAdress", (string)null);
                });

            modelBuilder.Entity("WebApplicationAchats.Models.Commande", b =>
                {
                    b.Property<int>("Numcom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NUMCOM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Numcom"));

                    b.Property<DateOnly?>("Datecom")
                        .HasColumnType("date")
                        .HasColumnName("DATECOM");

                    b.Property<int>("Numcli")
                        .HasColumnType("int")
                        .HasColumnName("NUMCLI");

                    b.HasKey("Numcom")
                        .HasName("pk_commande");

                    b.HasIndex("Numcli");

                    b.ToTable("COMMANDE", (string)null);
                });

            modelBuilder.Entity("WebApplicationAchats.Models.DetailCommande", b =>
                {
                    b.Property<int>("IdDetail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_DETAIL");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetail"));

                    b.Property<int>("IdCommande")
                        .HasColumnType("int")
                        .HasColumnName("ID_COMMANDE");

                    b.Property<int>("IdProduit")
                        .HasColumnType("int")
                        .HasColumnName("ID_PRODUIT");

                    b.Property<int?>("Quantite")
                        .HasColumnType("int")
                        .HasColumnName("QUANTITE");

                    b.HasKey("IdDetail")
                        .HasName("pk_detail");

                    b.HasIndex("IdCommande");

                    b.HasIndex("IdProduit");

                    b.ToTable("DETAIL_COMMANDE", (string)null);
                });

            modelBuilder.Entity("WebApplicationAchats.Models.Marque", b =>
                {
                    b.Property<int>("MarqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarqueId"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MarqueId");

                    b.ToTable("Marques");
                });

            modelBuilder.Entity("WebApplicationAchats.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategorieId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DateAjout")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("DATE_AJOUT")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<bool?>("Disponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("DISPONIBLE");

                    b.Property<int?>("MarqueId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nom");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("prix");

                    b.Property<int>("Quantite")
                        .HasColumnType("int")
                        .HasColumnName("quantite");

                    b.HasKey("Id")
                        .HasName("PK__produits__3213E83F6174ADA6");

                    b.HasIndex("CategorieId");

                    b.HasIndex("MarqueId");

                    b.ToTable("produits", (string)null);
                });

            modelBuilder.Entity("WebApplicationAchats.Models.Clientadress", b =>
                {
                    b.HasOne("WebApplicationAchats.Models.Client", "NumcliNavigation")
                        .WithOne("Clientadress")
                        .HasForeignKey("WebApplicationAchats.Models.Clientadress", "Numcli")
                        .IsRequired()
                        .HasConstraintName("fk_ClientAddr_Client");

                    b.Navigation("NumcliNavigation");
                });

            modelBuilder.Entity("WebApplicationAchats.Models.Commande", b =>
                {
                    b.HasOne("WebApplicationAchats.Models.Client", "NumcliNavigation")
                        .WithMany("Commandes")
                        .HasForeignKey("Numcli")
                        .IsRequired()
                        .HasConstraintName("fk_commande_client");

                    b.Navigation("NumcliNavigation");
                });

            modelBuilder.Entity("WebApplicationAchats.Models.DetailCommande", b =>
                {
                    b.HasOne("WebApplicationAchats.Models.Commande", "IdCommandeNavigation")
                        .WithMany("DetailCommandes")
                        .HasForeignKey("IdCommande")
                        .IsRequired()
                        .HasConstraintName("fk_detail_commande");

                    b.HasOne("WebApplicationAchats.Models.Produit", "IdProduitNavigation")
                        .WithMany("DetailCommandes")
                        .HasForeignKey("IdProduit")
                        .IsRequired()
                        .HasConstraintName("fk_detail_produit");

                    b.Navigation("IdCommandeNavigation");

                    b.Navigation("IdProduitNavigation");
                });

            modelBuilder.Entity("WebApplicationAchats.Models.Produit", b =>
                {
                    b.HasOne("WebApplicationAchats.Models.Categorie", "Categorie")
                        .WithMany("Produits")
                        .HasForeignKey("CategorieId");

                    b.HasOne("WebApplicationAchats.Models.Marque", "Marque")
                        .WithMany("Produits")
                        .HasForeignKey("MarqueId");

                    b.Navigation("Categorie");

                    b.Navigation("Marque");
                });

            modelBuilder.Entity("WebApplicationAchats.Models.Categorie", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("WebApplicationAchats.Models.Client", b =>
                {
                    b.Navigation("Clientadress");

                    b.Navigation("Commandes");
                });

            modelBuilder.Entity("WebApplicationAchats.Models.Commande", b =>
                {
                    b.Navigation("DetailCommandes");
                });

            modelBuilder.Entity("WebApplicationAchats.Models.Marque", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("WebApplicationAchats.Models.Produit", b =>
                {
                    b.Navigation("DetailCommandes");
                });
#pragma warning restore 612, 618
        }
    }
}
